name: Azure Static Web Apps CI/CD

on:
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to checkout"
        required: true
        type: string

jobs:
  build_and_deploy_job:
    if: github.event_name == 'pull_request' && github.event.action != 'closed' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Repository (PR Event)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true
          lfs: false

      - name: Checkout Repository (Manual Trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}
          submodules: true
          lfs: false

      - name: Tailwind CSS Build
        run: npm install && npx tailwindcss -i ./src/input.css -o ./src/style.css

      - name: Build Sitemap
        run: npm install sitemap && npx node ./scripts/generate-sitemap.js 

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.0.0
        with:
          directory: "src"
          add_suffix: false
          inclusions: |-
            .*css/*
            .*js/*

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/src/"
          api_location: "" 
          output_location: "/"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"