name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Tailwind CSS Build
        run: npm install && npx tailwindcss -i ./src/input.css -o ./src/style.css

      - name: Build Sitemap
        run: npm install sitemap && npx node ./scripts/generate-sitemap.js 

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.0.0
        with:
          directory: "src" # Optional
          add_suffix: false # Optional
          inclusions: |-
            .*css/*
            .*js/*

     # - name: Test if files exist
     #   run: ls ./src/css/

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/src/" # App source code path
          api_location: "" # Api source code path - optional 
          output_location: "/" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      #- name: Update Bing via IndexNow
      #  if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
      #  working-directory: "scripts"
      #  shell: bash
      #  run: ./indexnow.sh

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"